version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: aiplatform-util
    binary: aiplatform-util
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/vngcloud/aiplatform-util/cmd.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: vngcloud
    name: aiplatform-util
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
  footer: |
    ## Installation

    Download the appropriate binary for your platform:

    ### Linux (x86_64)
    ```bash
    curl -L https://github.com/vngcloud/aiplatform-util/releases/download/{{ .Tag }}/aiplatform-util_Linux_x86_64.tar.gz | tar xz
    chmod +x aiplatform-util
    sudo mv aiplatform-util /usr/local/bin/
    ```

    ### macOS (Intel)
    ```bash
    curl -L https://github.com/vngcloud/aiplatform-util/releases/download/{{ .Tag }}/aiplatform-util_Darwin_x86_64.tar.gz | tar xz
    chmod +x aiplatform-util
    sudo mv aiplatform-util /usr/local/bin/
    ```

    ### macOS (Apple Silicon)
    ```bash
    curl -L https://github.com/vngcloud/aiplatform-util/releases/download/{{ .Tag }}/aiplatform-util_Darwin_arm64.tar.gz | tar xz
    chmod +x aiplatform-util
    sudo mv aiplatform-util /usr/local/bin/
    ```
